#!/bin/sh

# This is for later if I ever figure out how to put colored text in the status bar
#NC='\033[0m'
#BLACK='\033[0;30m'
#BLACK_HI='\033[1;30m'
#BLACK_BG='\033[0;40m'
#BLACK_BG_HI='\033[1;40m'
#RED='\033[0;31m'
#RED_HI='\033[1;31m'
#GREEN='\033[0;32m'
#GREEN_HI='\033[1;32m'
#GREEN_BG='\033[0;42m'
#GREEN_HI_BG='\033[1;42m'
#YELLOW='\033[0;33m'
#YELLOW_HI='\033[1;33m'
#YELLOW_BG='\033[0;43m'
#YELLOW_HI_BG='\033[1;43m'
#BLUE='\033[0;34m'
#BLUE_HI='\033[1;34m'
#BLUE_BG='\033[0;44m'
#BLUE_HI_BG='\033[1;44m'
#MAGENTA='\033[0;35m'
#MAGENTA_HI='\033[1;35m'
#MAGENTA_BG='\033[0;45m'
#MAGENTA_HI_BG='\033[1;45m'
#CYAN='\033[0;36m'
#CYAN_HI='\033[1;36m'
#CYAN_BG='\033[0;46m'
#CYAN_HI_BG='\033[1;46m'
#WHITE='\033[0;37m'
#WHITE_HI='\033[1;37m'
#WHITE_BG='\033[0;47m'
#WHITE_HI_BG='\033[1;47m'

delim="|"

getVol(){
    if [ "$(amixer sget 'Master' | tail -n 1 | awk '{print $6}')" = "[off]" ]; then
        echo "[off]"
    else
        amixer sget 'Master' | tail -n 1 | awk '{print $5}'
    fi
}

getBat(){
    BAT_STAT="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/state/ {print $2}')"
    BAT_CAP="$(cat /sys/class/power_supply/BAT0/capacity)"
    if [ "$BAT_STAT" = "charging" ]
    then
        echo +"$BAT_CAP"
elif [ "$BAT_STAT" = "discharging" ]
    then
        echo -"$BAT_CAP"
    else
        echo "$BAT_CAP"
    fi
}

getUpdates() {
    UPDATE_TEXT="UPD: $NUM_UPDATES"
    if [ "$IMPORTANT_UPDATES" -gt 0 ]; then
        UPDATE_TEXT="$UPDATE_TEXT(I$IMPORTANT_UPDATES"
        if [ "$KERNEL_UPDATES" -gt 0 ]; then
            UPDATE_TEXT="${UPDATE_TEXT}L)"
        else
            UPDATE_TEXT="$UPDATE_TEXT)"
        fi
    elif [ "$KERNEL_UPDATES" -gt 0 ]; then
        UPDATE_TEXT="$UPDATE_TEXT(L)"
    fi

    echo "$UPDATE_TEXT"
}

status() {
    echo PAC: "$(pacman -Q | wc -l)"
    echo $delim
    getUpdates
    echo $delim
    echo Used: "$(df | awk '/\/dev\/nvme/ {print $5}')"
    echo $delim
    echo RAM: "$(free -m| awk '/^Mem/ {print $3"M/"$2"M"}')"
    echo $delim
    sensors | awk '/^Package/ {print $4}'|cut -c2-
    echo $delim
    echo Master: "$(getVol)"
    echo $delim
    echo BAT0: "$(getBat)"%
    echo $delim
    date '+%F %R'
}

while :; do
    xsetroot -name "$(status | tr '\n' ' ')"
    sleep 20
done
